### ISSUE TITLE
discuss and refine the 2017 project agenda

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/ambassador-board-room#11]
I've put together [a loose framework for our collective work in 2017](https://github.com/open-organization-ambassadors/ambassador-board-room/blob/master/ambassador-project-agenda.md), one built around the issues and projects we discussed at our in-person workshop in Raleigh, North Carolina, as part of All Things Open.

Let's take a look and refine it.

**Comment by whit537** [comment]
So helpful to see your strategic thinking for the year here, @semioticrobotic! What are your hopes and dreams in terms of the ambassadors themselves? What is your ideal number of ambassadors? Do you see any new ambassador recruiting happening in 2017?

**Comment by semioticrobotic** [comment]
Great questions, @whit537. I suppose the easiest answer to your first question (about hopes and dreams) is to say that I'm hoping the ambassadors see something on this list that resonates with them, something to which they feel they can add value, something they can help the group achieve—and, if they don't, to propose something that does! Here I tried to capture the items ambassadors said they thought most pressing and valuable when they met in person last October.

Most importantly, I hope this work helps us avoid the fate that so many ambassadors identified at that meeting—the one to which projects succumb when they talk, debate, generate great ideas ... and then ship nothing. maintaining a public, working project agenda to guide our work (and our monthly meetings) should help us mitigate that tendency.

As for recruiting: This is probably a discussion best conducted in tandem with our work on [v2.0 of the program description](https://github.com/open-organization-ambassadors/ambassador-program-description). Suffice it to say here, however, that I think inviting more people to the community is always a priority!

**Comment by whit537** [comment]
An idea I'll throw out there: I've been revisiting my cooperative roots lately (I helped start an organic growers cooperative back in 2002), and I've noticed some interesting parallels to our work and the sorts of conversations we started having in October.

Cooperativism is fundamentally defined as a set of [seven principles or values](http://ica.coop/en/whats-co-op/co-operative-identity-values-principles) (believe it or not, these date back to 1851—and the first is "open membership"!). There _is_ a [trademark](http://www.domains.coop/media/30691/terms_of_use_for_the_global_coop_marque.pdf) and a [TLD](http://www.nic.coop/), which require registration with a centralized authority in order to use. The process is lighter than the full requirements of a _legal_ entity (many jurisdictions do specify a cooperative legal form), but there is a process nonetheless. Cooperatives therefore offer an example of one optionb on the "toothiness" scale to consider as the #openorg conversation unfolds in the coming months and years.
