### ISSUE TITLE
consider opening up the publication pipeline

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#19]
Sounds from @semioticrobotic on our (private) monthly call like now might be a good time to start thinking about opening up the publication pipeline a bit more, in light of some related internal Red Hat changes. The main concern per @jhibbets is to manage expectations around headlines and publication dates, which can and do change on short notice. My understanding is that we'll approach this as we did the move to GitHub a few months ago: @semioticrobotic and I will put together a proposal, which we will then bring to the Ambassadors for discussion and feedback. If we can reach a consensus together then we can bring it to GitHub here for public review before finalizing our commitment and putting whatever we come up with into place.

**Comment by semioticrobotic** [comment]
Thanks, @whit537, for beginning this conversation, which I've been hoping to have ever since we first broached the subject at All Things Open in October 2016, but have not had the bandwidth or proper angle to do so. Now—in light of some productive changes to the way we (the Opensource.com editors, along with Jen Wike Huger, the site's content manager) handle the publication schedule here—I think we can.

To be clear, the problem I believe the community is attempting to solve is this: Ambassadors and other community members don't currently have sufficient visibility into the open organizational channel publication schedule or the current backlog of articles in the editorial queue. This is to say, the editorial/publishing process is not as transparent as it could be.

I'm in favor of greater transparency and other attempts at solving this problem. I think answers to the following questions would help the group move most productively toward doing so:

* **Why open the editorial process?** What are the benefits of opening the process, and what do we hope to gain by doing so? (I hasten to add here that I am not asking _if_ there is value in doing this—I believe there is—but rather _what_ specific improvements this affords, as that helps us imagine what the process might become.) From my perspective, I can think of a few benefits. Foremost, I think, it allows ambassadors to more proactively respond to article deficits. As it now stands, when our queue of available stories is low, I'm the only one who knows this, and the onus is on me alone to reach out to our community and drum up stories. If ambassadors could see the queue, then theoretically they could anticipate gaps or shortages and help fill them quicker. Second, this process allows ambassadors extra time to anticipate their publications and consider their pathways to sharing/promoting them. For example, if an ambassador knows she has an article appearing in, say, two weeks, then she can be ready for that publication day and help spread the word. As it now stands, sometimes articles pop onto the site and their authors learn about their publication only in that very moment.

* **What is an open editorial process?** Of course, we'll need to determine precisely what kind of "openness" we're talking about when we argue for "opening" the editorial process. Do ambassadors simply wish to see what's in the queue and on the horizon? Do they want to collaboratively edit the publication schedule? Write the headlines and/or subheads? Something else entirely? Understanding this helps us both shape the process and determine the best tools for facilitating it.

As Chad mentioned above (citing @jhibbets from earlier today), the biggest constraint on the editorial side is the need for flexibility. The Opensource.com publication calendar can change without much warning, in response to news events, the ebb and flow of stories we receive daily, strategy decisions, etc., and we'll just need to ensure that we do not add a level of overhead that detracts from our ability to stay nimble. All that said, I'm happy we're having this discussion.

**Comment by semioticrobotic** [comment]
Thinking more about this in advance of Thursday, @whit537, and wondering what you (or anyone else) thinks of the above.

**Comment by whit537** [comment]
I would +1 both the whys and the whats that you've articulated, and add that another reason to open up the publication schedule is to create the possibility of evolving co-ownership and responsibility. Who knows? With the publication schedule open to the community, we may surface one or two folks who, while they may not have new content to write themselves, may have editorial and managerial skills to offer. Opening up lets us find out.

As to the whats—did I hear you say at some point that you currently use Trello? That offers fairly fine-grained permissions, no? Can we use an access scheme parallel to what we have here on GitHub?

| Role | GitHub | Trello |
|:-----|:---------|:---------|
| anonymous | read issues and pull requests | read cards |
| authenticated | comment on issues and pull requests, submit pull requests | comment on cards |
| team member | label issues, merge pull requests, etc. | label cards, reprioritize, etc. |
| admin | grant permission to others | grant permission to others |

I think the fundamental shape of open source applies: just because a process is _transparent_ does not mean it is _anarchic_. No one submitting code to a project for the first time expects to have it accepted without comment (if they do, they're in for a surprise!). I don't see why the same wouldn't apply here. That is, if we create a public Trello board for the publication pipeline, I would expect the natural evolution to be that some folks start paying attention and commenting on cards, and gradually earn trust and thus responsibility in the editorial process. Most traffic will be read-only lurkers. A few will comment. A very few will contribute more deeply.

**Comment by semioticrobotic** [comment]
No qualms with or questions about any of the _what's_ and _why's_ you articulate here, @whit537. I really do think the biggest sticking point will be the _how_, in part because that's the part of the discussion that involves potential infrastructural changes to the process at Opensource.com headquarters.

But a prerequisite for the _how_ discussion is a robust _what_ discussion, because the _what_ will give shape to the specific functionality we require for addressing the _how_. For example, if ambassadors are primarily concerned with knowing which articles are scheduled for which dates, then a Trello board is overkill (because all we'd _need_ is some kind of public-facing spreadsheet). If ambassadors desire more interactivity and involvement, then something like Trello may be _exactly_ what we need. I'm open to suggestions; I just want to be sure we're making a good tool/purpose match. (And I do recognize the part of your argument that speaks to future-proofing the process and making it appealing to members we may not currently have or uses we don't currently see—but at this point I think we need to focus on some kind of MVP).

I should also point out that, yes, we do use Trello at Opensource.com—but that "we" is much larger than "me," and editorial matters are at the discretion of our content manager who runs the entire shebang. Opensource.com publishes roughly 100 articles per month, and not a single one goes online without Jen's helpful eye on it at least somewhere along the line. You'll recall from our monthly reports that open organization-themed articles account for nine or ten of those 100 articles per month (so about 10 percent of the monthly content). Because Jen has her Trello board running like a finely tuned machine that coordinates lots of secondary editors (like me), any Trello-related workflows we devise will need to add zero net new amount of overhead for the current content manager. I don't mind changing _my_ workflow to become more transparent about the open organization stories we're publishing, but I can't advocate anything broader than that for the time being. I know that no one asked me to do this, of course; I am just trying to make constraints and expectations clear (as we do).

**Comment by jenkelchner** [comment]
I'm +1 @whit537 on his above comment.  I personally don't want to dig too deep but agree it would be helpful to know what is in the works and upcoming.  For me, it might help in my accountability process as well as creative process.  :)

**Comment by whit537** [comment]
> That could be a Google Sheet, Doc, or another Trello board.

Heck, it could even be a [project board](https://github.com/open-organization-ambassadors/ambassador-board-room/projects) here on GitHub. 😁

**Comment by semioticrobotic** [comment]
Cool. Let me dig into the project board option and report back.

**Comment by semioticrobotic** [comment]
We now have a [public queue](https://github.com/orgs/open-organization-ambassadors/projects/1). Let's experiment with this and revisit when and if necessary.
