### ISSUE TITLE
ATO meetup?

### ISSUE THREAD

**Issue by whit537** [open-organization-ambassadors/ambassador-board-room#22]
@semioticrobotic @jhibbets Are we expecting another Ambassador meet-up during ATO like we did last year? If so, thoughts on dates? I'm starting to think about travel arrangements (since I'm speaking on @ruhbehka's panel! 💃 ) and am wondering how to plan ...

**Comment by semioticrobotic** [comment]
Thanks for checking in regarding this, @whit537. I can certainly understand your desire to get your travel plans in order right away.

Because of the timing of the conference this year, we aren't able to squeeze an official, all-day ambassador workshop into the pre-All Things Open agenda (as we did last year). However, a _number_ of ambassadors are going to be in town for the conference, so you can _sure bet_ that everyone who can (and would like to) will have an opportunity to get together. I'll contact everyone about that soon.
